displayName=Friends Online
author=robisa693
version=1.0.1
description=Shows an infobox on login with online friends, clan chat members, and chat channel members, including their worlds.
tags=friends,online,clan,chat,world,infobox,login
build=standard
plugins=com.robisa693.onlinefriends.FriendsOnlinePlugin
